"""图文笔记和公众号能力；账号编号与既有文章平台保持独立。"""

NOTE_PLATFORMS = frozenset(['jd', 'kuaishou', 'taobao', 'tencent', 'xiaohongshu', 'xiaohongshu_merchant'])

NOTE_PLATFORM_RULES = {'xiaohongshu': {'label': '小红书',
                 'account_type': 1,
                 'title_min': 1,
                 'title_max': 20,
                 'cover_required': False,
                 'cover_max_bytes': 20971520,
                 'cover_min_width': 0,
                 'cover_min_height': 0,
                 'statement_options': [],
                 'body_max_chars': 1000,
                 'body_max_images': 18,
                 'tags_max': 10,
                 'content_kind': '图文笔记',
                 'content_mode': 'image_text',
                 'limitations': '至少一张图片；封面未出现在正文中时放在图片列表首位。描述与图片分开展示，链接保留为文字和完整网址；富文本排版须明确同意转换。话题按 #文字 写入描述。',
                 'option_fields': [{'name': 'flatten_content',
                                    'label': '将富文本转换为纯文本描述和图片列表',
                                    'type': 'boolean'}]},
 'kuaishou': {'label': '快手',
              'account_type': 4,
              'title_min': 1,
              'title_max': 90,
              'cover_required': False,
              'cover_max_bytes': 20971520,
              'cover_min_width': 0,
              'cover_min_height': 0,
              'statement_options': [],
              'body_max_chars': 500,
              'body_max_images': 30,
              'tags_max': 5,
              'content_kind': '图文笔记',
              'content_mode': 'image_text',
              'limitations': '至少一张图片；封面未出现在正文中时放在图片列表首位。描述与图片分开展示，链接保留为文字和完整网址；富文本排版须明确同意转换。话题按 #文字 '
                             '写入描述。快手标题写入描述首行，与正文和话题一并计入字数。',
              'option_fields': [{'name': 'flatten_content',
                                 'label': '将富文本转换为纯文本描述和图片列表',
                                 'type': 'boolean'}]},
 'tencent': {'label': '视频号',
             'account_type': 2,
             'title_min': 1,
             'title_max': 16,
             'cover_required': False,
             'cover_max_bytes': 20971520,
             'cover_min_width': 0,
             'cover_min_height': 0,
             'statement_options': [],
             'body_max_chars': 1000,
             'body_max_images': 9,
             'tags_max': 5,
             'content_kind': '图文笔记',
             'content_mode': 'image_text',
             'limitations': '至少一张图片；封面未出现在正文中时放在图片列表首位。描述与图片分开展示，链接保留为文字和完整网址；富文本排版须明确同意转换。话题按 #文字 写入描述。',
             'option_fields': [{'name': 'flatten_content', 'label': '将富文本转换为纯文本描述和图片列表', 'type': 'boolean'}]},
 'wechat': {'label': '微信公众号',
            'account_type': 25,
            'title_min': 1,
            'title_max': 64,
            'cover_required': True,
            'cover_max_bytes': 10485760,
            'cover_min_width': 0,
            'cover_min_height': 0,
            'statement_options': [],
            'limitations': '暂不支持原生话题，请在账号设置中清空话题；发表可能需要管理员扫码确认。保存草稿不代表已发表。',
            'content_kind': '公众号图文',
            'content_mode': 'rich_article',
            'option_fields': [{'name': 'author', 'label': '作者', 'type': 'text', 'max_length': 8},
                              {'name': 'summary', 'label': '摘要', 'type': 'textarea', 'max_length': 120}]},
 'jd': {'label': '京东图文',
        'account_type': 26,
        'title_min': 5,
        'title_max': 20,
        'cover_required': False,
        'cover_max_bytes': 5242880,
        'cover_min_width': 0,
        'cover_min_height': 0,
        'statement_options': [],
        'body_max_chars': 1000,
        'body_max_images': 20,
        'cover_is_first_image': True,
        'content_kind': '图文笔记',
        'content_mode': 'image_text',
        'limitations': '至少一张图片；封面未出现在正文中时放在图片列表首位。描述与图片分开展示，链接保留为文字和完整网址；富文本排版须明确同意转换。话题按 #文字 '
                       '写入描述。首图自动生成封面，已在正文中的所选封面必须是首图；每张图片最多 5 MB，关联商品按当前频道要求校验。',
        'option_fields': [{'name': 'flatten_content', 'label': '将富文本转换为纯文本描述和图片列表', 'type': 'boolean'},
                          {'name': 'product_links',
                           'label': '关联商品',
                           'type': 'textarea',
                           'max_length': 2000,
                           'placeholder': '填写京东商品链接或 SKU，用换行或逗号分隔，最多 10 个'}]},
 'xiaohongshu_merchant': {'label': '小红书商家号',
                          'account_type': 27,
                          'title_min': 1,
                          'title_max': 20,
                          'cover_required': False,
                          'cover_max_bytes': 20971520,
                          'cover_min_width': 0,
                          'cover_min_height': 0,
                          'statement_options': [],
                          'body_max_chars': 1000,
                          'body_max_images': 9,
                          'tags_max': 10,
                          'content_kind': '图文笔记',
                          'content_mode': 'image_text',
                          'limitations': '至少一张图片；封面未出现在正文中时放在图片列表首位。描述与图片分开展示，链接保留为文字和完整网址；富文本排版须明确同意转换。话题按 '
                                         '#文字 写入描述。使用独立商家账号；须填写准确店铺名和商品 ID。图片采用 9 张保守上限。',
                          'option_fields': [{'name': 'flatten_content',
                                             'label': '将富文本转换为纯文本描述和图片列表',
                                             'type': 'boolean'},
                                            {'name': 'product_id',
                                             'label': '关联商品 ID',
                                             'type': 'text',
                                             'required': True,
                                             'max_length': 64,
                                             'placeholder': '填写该店铺中要关联的准确商品 ID'},
                                            {'name': 'shop_name',
                                             'label': '店铺名称',
                                             'type': 'text',
                                             'required': True,
                                             'max_length': 100,
                                             'placeholder': '填写商家后台显示的完整店铺名称'}]},
 'taobao': {'label': '淘宝光合',
            'account_type': 28,
            'title_min': 1,
            'title_max': 30,
            'cover_required': False,
            'cover_max_bytes': 20971520,
            'cover_min_width': 0,
            'cover_min_height': 0,
            'statement_options': ['内容无需标注', '含AI生成内容', '含虚构演绎内容', '内容为转载', '个人观点，仅供参考', '内容含营销信息'],
            'statement_required': True,
            'tags_supported': False,
            'body_max_chars': 1000,
            'body_max_images': 9,
            'cover_is_first_image': True,
            'image_min_width': 720,
            'image_min_height': 720,
            'content_kind': '图文笔记',
            'content_mode': 'image_text',
            'limitations': '每张图片至少 720×720，首图为封面，最多 9 '
                           '张；已在正文中的所选封面必须是首图。富文本转为描述须明确同意。须选择创作者声明；暂不支持关联商品和原生内容标签，请清空话题。',
            'option_fields': [{'name': 'flatten_content', 'label': '将富文本转换为纯文本描述和图片列表', 'type': 'boolean'},
                              {'name': 'statement',
                               'label': '创作声明',
                               'type': 'select',
                               'options': ['内容无需标注', '含AI生成内容', '含虚构演绎内容', '内容为转载', '个人观点，仅供参考', '内容含营销信息'],
                               'required': True}]}}
